packages:
  - 'packages/chained-iterator'
  - 'packages/chronograph'
  - 'packages/dev-scripts'
  - 'packages/siesta'
  - 'packages/siesta-example-browser'
  - 'packages/siesta-example-deno'
  - 'packages/siesta-example-isomorphic'
  - 'packages/siesta-example-nodejs'
  - 'packages/typescript-mixin-class'
  - 'packages/typescript-serializable-mixin'
