export const styles = new Map()

styles.set('diff-atomic-not-same', style => { style.color = [ 0xf6, 0xb1, 0x08 ] })
styles.set('diff-not-same', style => { style.bold = true })
styles.set('diff-same', style => { style.color = [ 0x93, 0x93, 0x93 ] })
styles.set('diff-only-in-1', style => { style.color = [ 0xf9, 0x64, 0x3f ] })
styles.set('diff-only-in-2', style => { style.color = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('diff-hetero', style => { style.color = [ 0xf6, 0xb1, 0x08 ] })
styles.set('underline', style => { style.underline = true })
styles.set('gray', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('secondary_pass', style => { style.color = [ 0xfa, 0xcb, 0x5a ] })
styles.set('secondary_pass_lighter', style => { style.color = [ 0xfb, 0xd8, 0x83 ] })
styles.set('secondary_fail', style => { style.color = [ 0xfc, 0xa1, 0x59 ] })
styles.set('primary_pass', style => { style.color = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('primary_pass_lighter', style => { style.color = [ 0x22, 0xf3, 0xd9 ] })
styles.set('primary_fail', style => { style.color = [ 0xf9, 0x64, 0x3f ] })
styles.set('primary_fail_darker', style => { style.color = [ 0xe3, 0x33, 0x07 ] })
styles.set('secondary_pass_lighter', style => { style.color = [ 0xfb, 0xd8, 0x83 ] })
styles.set('accented', style => { style.bold = true })
styles.set('inverse', style => { style.inverse = true })
styles.set('deccented', style => { style.color = [ 0x0a, 0x52, 0x70 ] })
styles.set('project_title', style => { style.underline = true })
styles.set('test_file_url_dirname', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('test_file_url_filename', style => { style.bold = true })
styles.set('test_file_pass', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('test_file_fail', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0xf9, 0x64, 0x3f ] })
styles.set('test_file_runs', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0xfa, 0xcb, 0x5a ] })
styles.set('sub_test_pass', style => { style.color = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('sub_test_fail', style => { style.color = [ 0xf9, 0x64, 0x3f ] })
styles.set('sub_test_runs', style => { style.color = [ 0xfa, 0xcb, 0x5a ] })
styles.set('assertion_icon_pass_todo', style => { style.color = [ 0xfc, 0xa1, 0x59 ] })
styles.set('assertion_icon_pass', style => { style.color = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('assertion_icon_fail', style => { style.color = [ 0xf9, 0x64, 0x3f ] })
styles.set('assertion_name', style => { style.color = [ 0xfa, 0xcb, 0x5a ] })
styles.set('assertion_source_line', style => { style.color = [ 0xfa, 0xcb, 0x5a ] })
styles.set('assertion_description', style => { style.bold = true })
styles.set('log_message_icon', style => { style.color = [ 0xfc, 0xa1, 0x59 ] })
styles.set('log_message_error', style => { style.backgroundColor = [ 0xf9, 0x64, 0x3f ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_warn', style => { style.backgroundColor = [ 0xfc, 0xa1, 0x59 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_log', style => { style.backgroundColor = [ 0xfa, 0xcb, 0x5a ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_debug', style => { style.backgroundColor = [ 0x0b, 0xbd, 0xa7 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_info', style => { style.backgroundColor = [ 0x0a, 0x52, 0x70 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('exception_icon', style => { style.backgroundColor = [ 0xf9, 0x64, 0x3f ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('summary', style => { style.bold = true })
styles.set('summary_tests_passed', style => { style.color = [ 0x0b, 0xbd, 0xa7 ] })
styles.set('summary_tests_failed', style => { style.color = [ 0xf9, 0x64, 0x3f ] })
styles.set('progress_bar_completed_passed', style => { style.backgroundColor = [ 0x08, 0x8d, 0x7d ] })
styles.set('progress_bar_completed_failed', style => { style.backgroundColor = [ 0xe3, 0x33, 0x07 ] })
styles.set('typename', style => { style.color = [ 0xfa, 0xcb, 0x5a ] })
styles.set('tree_line', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('accented_value', style => { style.color = [ 0xfb, 0xd8, 0x83 ] })
styles.set('option_name', style => { style.bold = true })
styles.set('option_group_name', style => { style.color = [ 0x0b, 0xbd, 0xa7 ]; style.bold = true })