export const styles = new Map()

styles.set('diff-atomic-not-same', style => { style.color = [ 0xde, 0xa7, 0x21 ] })
styles.set('diff-not-same', style => { style.bold = true })
styles.set('diff-same', style => { style.color = [ 0x93, 0x93, 0x93 ] })
styles.set('diff-only-in-1', style => { style.color = [ 0xe7, 0x6f, 0x51 ] })
styles.set('diff-only-in-2', style => { style.color = [ 0x2a, 0x9d, 0x8f ] })
styles.set('diff-hetero', style => { style.color = [ 0xde, 0xa7, 0x21 ] })
styles.set('underline', style => { style.underline = true })
styles.set('gray', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('secondary_pass', style => { style.color = [ 0xe9, 0xc4, 0x6a ] })
styles.set('secondary_pass_lighter', style => { style.color = [ 0xef, 0xd3, 0x8f ] })
styles.set('secondary_fail', style => { style.color = [ 0xf4, 0xa2, 0x61 ] })
styles.set('primary_pass', style => { style.color = [ 0x2a, 0x9d, 0x8f ] })
styles.set('primary_pass_lighter', style => { style.color = [ 0x47, 0xce, 0xbd ] })
styles.set('primary_fail', style => { style.color = [ 0xe7, 0x6f, 0x51 ] })
styles.set('primary_fail_darker', style => { style.color = [ 0xce, 0x40, 0x1c ] })
styles.set('secondary_pass_lighter', style => { style.color = [ 0xef, 0xd3, 0x8f ] })
styles.set('accented', style => { style.bold = true })
styles.set('inverse', style => { style.inverse = true })
styles.set('deccented', style => { style.color = [ 0x26, 0x46, 0x53 ] })
styles.set('project_title', style => { style.underline = true })
styles.set('test_file_url_dirname', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('test_file_url_filename', style => { style.bold = true })
styles.set('test_file_pass', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0x2a, 0x9d, 0x8f ] })
styles.set('test_file_fail', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0xe7, 0x6f, 0x51 ] })
styles.set('test_file_runs', style => { style.color = [ 0x00, 0x00, 0x00 ]; style.backgroundColor = [ 0xe9, 0xc4, 0x6a ] })
styles.set('sub_test_pass', style => { style.color = [ 0x2a, 0x9d, 0x8f ] })
styles.set('sub_test_fail', style => { style.color = [ 0xe7, 0x6f, 0x51 ] })
styles.set('sub_test_runs', style => { style.color = [ 0xe9, 0xc4, 0x6a ] })
styles.set('assertion_icon_pass_todo', style => { style.color = [ 0xf4, 0xa2, 0x61 ] })
styles.set('assertion_icon_pass', style => { style.color = [ 0x2a, 0x9d, 0x8f ] })
styles.set('assertion_icon_fail', style => { style.color = [ 0xe7, 0x6f, 0x51 ] })
styles.set('assertion_name', style => { style.color = [ 0xe9, 0xc4, 0x6a ] })
styles.set('assertion_source_line', style => { style.color = [ 0xe9, 0xc4, 0x6a ] })
styles.set('assertion_description', style => { style.bold = true })
styles.set('log_message_icon', style => { style.color = [ 0xf4, 0xa2, 0x61 ] })
styles.set('log_message_error', style => { style.backgroundColor = [ 0xe7, 0x6f, 0x51 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_warn', style => { style.backgroundColor = [ 0xf4, 0xa2, 0x61 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_log', style => { style.backgroundColor = [ 0xe9, 0xc4, 0x6a ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_debug', style => { style.backgroundColor = [ 0x2a, 0x9d, 0x8f ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('log_message_info', style => { style.backgroundColor = [ 0x26, 0x46, 0x53 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('exception_icon', style => { style.backgroundColor = [ 0xe7, 0x6f, 0x51 ]; style.color = [ 0x00, 0x00, 0x00 ] })
styles.set('summary', style => { style.bold = true })
styles.set('summary_tests_passed', style => { style.color = [ 0x2a, 0x9d, 0x8f ] })
styles.set('summary_tests_failed', style => { style.color = [ 0xe7, 0x6f, 0x51 ] })
styles.set('progress_bar_completed_passed', style => { style.backgroundColor = [ 0x20, 0x76, 0x6b ] })
styles.set('progress_bar_completed_failed', style => { style.backgroundColor = [ 0xce, 0x40, 0x1c ] })
styles.set('typename', style => { style.color = [ 0xe9, 0xc4, 0x6a ] })
styles.set('tree_line', style => { style.color = [ 0x80, 0x80, 0x80 ] })
styles.set('accented_value', style => { style.color = [ 0xef, 0xd3, 0x8f ] })
styles.set('option_name', style => { style.bold = true })
styles.set('option_group_name', style => { style.color = [ 0x2a, 0x9d, 0x8f ]; style.bold = true })
